# Generated by Django 5.1.4 on 2024-12-25 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='mobile',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
