# Generated by Django 5.1.4 on 2024-12-27 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_alter_studentprofile_mobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='gender',
            field=models.CharField(blank=True, default='Male', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='qualification',
            field=models.CharField(blank=True, default='Others', max_length=500, null=True),
        ),
    ]
