# Generated by Django 5.1.4 on 2024-12-27 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_studentprofile_gender_studentprofile_qualification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='place',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
