# Generated by Django 5.1.4 on 2024-12-27 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_alter_studentprofile_place'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='mobile',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
