# Generated by Django 5.1.4 on 2025-02-09 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0013_message_is_read_message_recipient_alter_message_room_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.DeleteModel(
            name='UserStatus',
        ),
    ]
