# Generated by Django 5.1.4 on 2025-02-14 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0016_notification_delete_studentnotification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('message', 'Message'), ('online', 'Online')], max_length=50),
        ),
    ]
