# Generated by Django 5.1.4 on 2025-02-20 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0018_remove_progress_enrolled_course_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progress',
            name='time_watched',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
