# Generated by Django 5.1.4 on 2025-02-20 05:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_alter_courses_description'),
        ('student', '0019_alter_progress_time_watched'),
    ]

    operations = [
        migrations.AddField(
            model_name='progress',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='courses.courses'),
        ),
        migrations.AlterField(
            model_name='progress',
            name='time_watched',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
