# Generated by Django 5.1.4 on 2025-03-04 16:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0023_order_payment_id_order_payment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrolledcourses',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='student.order'),
        ),
    ]
