# Generated by Django 5.1.4 on 2025-03-05 11:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0024_enrolledcourses_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrolledcourses',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='student.order_items'),
        ),
    ]
