# Generated by Django 5.1.4 on 2025-03-05 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0025_alter_enrolledcourses_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_items',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.RemoveField(
            model_name='enrolledcourses',
            name='order',
        ),
        migrations.AddField(
            model_name='enrolledcourses',
            name='order',
            field=models.ManyToManyField(blank=True, null=True, to='student.order_items'),
        ),
    ]
