# Generated by Django 5.1.4 on 2025-04-10 12:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0014_alter_courses_teacher'),
        ('student', '0027_alter_enrolledcourses_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_items',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='courses.courses'),
        ),
    ]
