# Generated by Django 5.1.4 on 2025-04-19 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0028_alter_order_items_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
