# Generated by Django 5.1.4 on 2025-04-25 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0029_studentprofile_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
