# Generated by Django 5.1.4 on 2025-05-22 07:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0030_alter_studentprofile_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='user_state',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='order_items',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_order_items', to='student.order'),
        ),
    ]
