# Generated by Django 5.1.4 on 2026-01-27 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0032_pendingpayment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pendingpayment',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
