# Generated by Django 5.1.4 on 2025-02-24 16:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_userstatus'),
        ('courses', '0008_ratingstar'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(default='New course submitted for approval.')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('is_seen', models.BooleanField(default=False)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.courses')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sende_notifications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
