# Generated by Django 5.1.4 on 2025-02-25 09:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_adminnotification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminnotification',
            name='message',
            field=models.TextField(blank=True, default='New course submitted for approval.'),
        ),
        migrations.AlterField(
            model_name='adminnotification',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender_notifications', to=settings.AUTH_USER_MODEL),
        ),
    ]
