# Generated by Django 5.1.4 on 2024-12-30 18:16

import courses.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_courses_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='date_created',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='courses',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to=courses.models.upload_to),
        ),
    ]
