# Generated by Django 5.1.4 on 2025-01-10 17:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_courses_offer_price_courses_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Modules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(blank=True, null=True)),
                ('topic', models.CharField(blank=True, max_length=2000, null=True)),
                ('sub_topic', models.CharField(blank=True, max_length=2000, null=True)),
                ('media', models.URLField(blank=True, null=True)),
                ('total_time', models.BigIntegerField(blank=True, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.courses')),
            ],
        ),
    ]
