# Generated by Django 5.1.4 on 2025-01-13 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_modules'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='cover_text',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
