# Generated by Django 5.1.4 on 2025-01-20 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_courses_cover_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='description',
            field=models.CharField(blank=True, max_length=50000, null=True),
        ),
    ]
