# Generated by Django 5.1.4 on 2025-02-26 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_courses_visible_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='modules',
            name='video_path',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
