# Generated by Django 5.1.4 on 2025-02-26 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_modules_video_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='modules',
            name='processing_status',
            field=models.CharField(default='Pending', max_length=50),
        ),
    ]
