# Generated by Django 5.1.4 on 2025-02-27 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_modules_processing_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='modules',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
