# Generated by Django 5.1.4 on 2025-02-28 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_modules_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='visible_status',
            field=models.CharField(choices=[('public', 'Public'), ('private', 'Private'), ('waiting', 'waiting')], default='waiting', max_length=10),
        ),
    ]
