# Generated by Django 5.1.4 on 2025-03-13 09:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_alter_courses_visible_status'),
        ('teacher', '0004_alter_teacherprofile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='teacher.teacherprofile'),
        ),
    ]
