# Generated by Django 5.1.4 on 2025-04-21 15:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0014_alter_courses_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='visible_status',
            field=models.CharField(choices=[('public', 'Public'), ('private', 'Private'), ('waiting', 'Waiting'), ('Put on Hold', 'Put on Hold'), ('Rejected', 'Rejected')], default='waiting', max_length=100),
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_status', models.CharField(choices=[('public', 'Public'), ('private', 'Private'), ('waiting', 'Waiting'), ('put_on_hold', 'Put on Hold'), ('rejected', 'Rejected')], default='waiting', max_length=20)),
                ('reason', models.CharField(blank=True, max_length=50000, null=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.courses')),
            ],
        ),
    ]
