# Generated by Django 5.1.4 on 2025-04-22 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0015_alter_courses_visible_status_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='visible_status',
            field=models.CharField(choices=[('public', 'Public'), ('private', 'Private'), ('waiting', 'Waiting'), ('Put on Hold', 'Put on Hold'), ('Rejected', 'Rejected')], default='private', max_length=100),
        ),
        migrations.AlterField(
            model_name='status',
            name='course_status',
            field=models.CharField(choices=[('public', 'Public'), ('private', 'Private'), ('waiting', 'Waiting'), ('put_on_hold', 'Put on Hold'), ('rejected', 'Rejected')], default='private', max_length=20),
        ),
    ]
