# Generated by Django 5.1.4 on 2025-04-22 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0016_alter_courses_visible_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='required',
            field=models.CharField(blank=True, max_length=50000, null=True),
        ),
    ]
