# Generated by Django 5.1.4 on 2025-04-23 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0017_status_required'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='visible_status',
            field=models.CharField(choices=[('public', 'Public'), ('private', 'Private'), ('waiting', 'Waiting'), ('Hold', 'Hold'), ('Rejected', 'Rejected')], default='private', max_length=100),
        ),
        migrations.AlterField(
            model_name='status',
            name='course_status',
            field=models.CharField(choices=[('public', 'Public'), ('private', 'Private'), ('waiting', 'Waiting'), ('hold', 'Hold'), ('rejected', 'Rejected')], default='private', max_length=20),
        ),
    ]
