# Generated by Django 5.1.4 on 2025-04-23 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0018_alter_courses_visible_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='visible_status',
            field=models.CharField(choices=[('Public', 'Public'), ('Private', 'Private'), ('Waiting', 'Waiting'), ('Hold', 'Hold'), ('Rejected', 'Rejected')], default='Private', max_length=100),
        ),
        migrations.AlterField(
            model_name='status',
            name='course_status',
            field=models.CharField(choices=[('Public', 'Public'), ('Private', 'Private'), ('Waiting', 'Waiting'), ('Hold', 'Hold'), ('Rejected', 'Rejected')], default='Private', max_length=20),
        ),
    ]
