# Generated by Django 5.1.4 on 2024-12-27 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherprofile',
            name='gender',
            field=models.CharField(default='Male', max_length=100),
        ),
    ]
