# Generated by Django 5.1.4 on 2024-12-29 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0002_teacherprofile_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherprofile',
            name='experience_in',
            field=models.CharField(blank=True, default='None', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='teacherprofile',
            name='experience',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
